name: CI/CD Deployment Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  GCP_REGION: us-central1
  GCP_SERVICE_NAME: recommendation-api
  ARTIFACT_REPO: byteflix
  PROJECT_ID: byteflix-project

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: pytest || true  

  build-and-push:
    name: Build and Push to Google Artifact Registry
    needs: lint-and-test
    runs-on: ubuntu-latest
    environment: production 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.GCP_SERVICE_NAME }}:latest

  deploy:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production  
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Deploy to Cloud Run
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_SERVICE_NAME }}
          region: ${{ env.GCP_REGION }}
          image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.GCP_SERVICE_NAME }}:latest

          secrets: |-
            KAFKA_BOOTSTRAP=KAFKA_BOOTSTRAP:latest
            KAFKA_API_KEY=KAFKA_API_KEY:latest
            KAFKA_API_SECRET=KAFKA_API_SECRET:latest
            SCHEMA_REGISTRY_URL=SCHEMA_REGISTRY_URL:latest

      - name: Output Deployed URL
        run: echo "Deployed to ${{ steps.deploy-service.outputs.url }}"
